-- AlterTable
ALTER TABLE `order` ADD COLUMN `paidAt` DATETIME(3) NULL,
    ADD COLUMN `paymentProof` LONGTEXT NULL,
    MODIFY `status` ENUM('PENDING', 'WAITING_PAYMENT', 'PAYMENT_REVIEW', 'PAID', 'DELIVERING', 'DELIVERED', 'CANCELLED', 'CONFIRMED', 'COMPLETED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `otpCode` VARCHAR(191) NULL,
    ADD COLUMN `otpExpiry` DATETIME(3) NULL;
